//
//  listArrays.swift
//  XHover
//
//  Created by Luis Gonzalez on 8/6/21.
//

import Foundation
import UIKit

let topSellerList = ["BLASTR V2", "XHOVER BLASTR HD BNF 6S V2", "CINE X BNF (HD OR ANALOG)", "CINE X BNF (HD CADDX VERSION)"]

let discriptionList = ["The Blastr V2 builds off the simplicity of the original and makes it even easier to fly. With added compatibility for the full size Air Unit, there's no need to remove standoffs. V2 features backwards compatible 6 inch arms to allow more prop options. The Blastr V2 was designed with the new Lift Kit system in mind. Upgrade your quadcopter and turn it into a fully capable 8 rotor!", "We are proud to offer thew Xhover Blastr V2 in a HD BNF version! Featuring the best components installed and tuned! This Blastr V2 HD comes with everything you need to start flying and start getting some exciting Cinematic shots!\n\n The components we have chosen for this build are some of the best out on the market. They have been fine-tuned and even used by the pros. The Blastr features a BrainFPV  flight controller that is fine-tuned along with a bulletproof 4-1 ESC that supports 4-6s packs.\n\n The Blastr HD version comes with DJI's all-new Digital FPV system. Experience 720p 120fps via the DJI goggles! 7ms extremely low latency the image. The experince of this setup will blow you away! ", "We are extremely proud to introduce our latest airframe the Cine-X We know that many of you out there want to produce some fantastic aerial footage and that is the inspiration for the Cine-X. Designed for a DJI Air Unit and a 20x20 stack up front or back, this micro frame can produce some incredible stable footage.\n\n BNF version comes fully built tuned and test flown here in the USA to maximize quality and bring you something that flys amazing out of the box! ", "We are extremely proud to introduce our latest airframe the Cine-X We know that many of you out there want to produce some fantastic aerial footage and that is the inspiration for the Cine-X.\n\n BNF version comes fully built tuned and test flown here in the USA to maximize quality and bring you something that flys amazing out of the box! "]

let includeList = ["1x Blastr 5 Frame\n1x DJI Air unit mount\n1x DJI antenna mount\n2x GoPro Hero 8/9 mounts\n1x FPV Camera mount\n1x Battery Pad\n1x Battery Strap"]

let tipDiscrip = ["Don’t use cheap VTXs if you want to race. This is the most important one for beginners – to the extent that most races put a requirement on it. The problem with the cheap ones is that they spray all over the frequency band and mess up other racers video feeds. Avoid the ones with huge SMA connectors sticking out the back, and the ones that don’t support Smartaudio or Tramp. For a racing quad you should avoid SMA antennas altogether and use their smaller MMCX or even better U.FL versions.\n\n> What I recommend is the $30 and up range like the TBS Unify Pro HV 5G8 – Race paired with a TBS Triumph Pro U.FL. Need something smaller? There’s the TBS Unify Pro 5G8 V3 (SMA), implying that you replace the U.FL to SMA pigtail with a U.FL antenna. What’s nice about the TBS ones is they work well if you’re using Crossfire or Tracer. This saves you a lot of headaches when it comes to setting up Smartaudio. You just solder the VTX Smartaudio wire directly to the Nano RX of your choice. And then you can change your VTX settings on your radio using TBS Agent Lite or with the screen on the back of the Crossfire LITE module if that’s the one you happen to be using. Or even directly on your goggles if you’re using a TBS Fusion receiver module.\n\n> If you’re using ImmersionRC Ghost, a good choice of VTX is the tried and true Tramp Nano. Disclaimer: I haven’t tried Ghost or Tracer, I’ve only ever flown on Crossfire, so I’m not a 100% sure on how it works, but Ghost should have a way to change the VTX settings.\n\nBut why is Smartaudio/Tramp a must? Because the classic way to change VTX settings is to wire it to the FC, using up a UART port, then having to set it up on the FC (VTX tables?😱)\n\n so that you can go through the struggle of navigating the OSD in your goggles every time you need to change your VTX settings.","","","",""]
